name: Node.js CI/CD

on:
  push:
    branches: [ master ] # or your main branch name
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16,20] # Test across different Node versions

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache node modules

      - name: Install dependencies
        run: npm ci # Use npm ci for faster and more reliable installs

      - name: Run tests
        run: npm test # Your test command (e.g., npm run test, jest, mocha)